substitutions:
  name: 'backlit-frame'
  friendly_name: 'Backlit Frame'
  delay_time: 60s

esphome:
  name: '${name}'
  name_add_mac_suffix: true

packages:
  base_config: !include ../../common/base_config.yaml
  wifi_fallback: !include ../../common/wifi_fallback.yaml
  common_sensors: !include ../../common/common_sensors.yaml

ota:
  - platform: esphome
    password: !secret ota_password

# Board
esp8266:
  board: esp01_1m
  framework:
    version: recommended


# Begin

switch:
  - platform: gpio
    pin: GPIO0
    id: gpio_0
    name: '${friendly_name} Light'
    inverted: true

  - platform: restart
    name: '${friendly_name} Restart'

script:
  - id: pir_timer
    mode: restart
    then:
      - switch.turn_on: gpio_0
      - delay: ${delay_time}
      - switch.turn_off: gpio_0


binary_sensor:
  # pullup: false. Make sure PIR input is low when not detected.
  - platform: gpio
    name: '${friendly_name} PIR'
    id: 'thisPIR'
    device_class: motion
    pin: 
      number: GPIO3
      mode:
        input: true
        pullup: false
    on_press:
      then:
        - script.execute: pir_timer
