substitutions:
  name: 'garage-opener'
  friendly_name: 'Garage Opener'

esphome:
  name: '${name}'
  name_add_mac_suffix: true

packages:
  base_config: !include ../../common/base_config.yaml
  wifi_fallback: !include ../../common/wifi_fallback.yaml
  common_sensors: !include ../../common/common_sensors.yaml

esp8266:
  board: esp01_1m
  framework:
    version: recommended

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO14
      mode:
        input: true
        pullup: true
    inverted: true
    name: "${friendly_name} Door Sensor"
    device_class: garage_door
    
  - platform: template
    name: "Equinox"
    icon: "mdi:car"
    device_class: presence
    lambda: |-
      if (id(uss_garage).state < 1.0) {
        // car is in the garage
        return true;
      } else {
        // no car
        return false;
      }   
      
switch:
  - platform: gpio
    pin: GPIO12
    id: relay
  - platform: template
    icon: "mdi:arrow-up-down-bold-outline"
    name: "${friendly_name} Door Opener"
    turn_on_action:
    - switch.turn_on: relay
    - delay: 500ms
    - switch.turn_off: relay

sensor:
  - platform: ultrasonic
    id: uss_garage
    trigger_pin: GPIO05
    echo_pin: GPIO04
    name: "${friendly_name} Car Detector"
    update_interval: 60s
    filters:
      filter_out: nan
    timeout: 9m
