substitutions:
  hostname: 'esp32'
  board: 'nodemcu-32s'
   

esphome:
  name: $hostname
  name_add_mac_suffix: true


esp32:
  board: ${board}


# Enable logging
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # use_address: cam-1.local

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: 'hotspot.$hostname.hotspot' 
    password: "jEvC7RTUNb7X"


# Enable Home Assistant API
api:
  encryption:
    key: "KytqgkyuUV5z/ofXcgfC0e+7cEajkDI+yhw1GA6N5Ro="

ota:
  password: !secret ota_password


# Enable logging
logger:

# This feature is only available with frameworks ['arduino'].
captive_portal:
    
    


# Media_player      
# This feature is only available with frameworks ['arduino'].
media_player:
  - platform: i2s_audio
    name: '$hostname I2S Media Player'
    dac_type: external
    i2s_lrclk_pin: GPIO05
    i2s_dout_pin: GPIO18
    i2s_bclk_pin: GPIO19
    mode: stereo
    

# pcm5102  ESP32
# LRCK  i2s_lrclk_pin
# DIN   i2s_dout_pin
# BCK   i2s_bclk_pin
# VIN   3V3
# GND   GND


# Common
output:
    # Red statuslight
  - platform: gpio
    pin:
      number: GPIO02
      inverted: False
    id: gpio_blue

light:
  - platform: binary
    output: gpio_blue
    name: '$hostname Blue'
    
switch:
  - platform: restart
    name: '$hostname restart'


binary_sensor:
  - platform: status
    name: '$hostname status'
    
sensor:
  - platform: wifi_signal
    name: '$hostname WiFi Signal'
