# WiFi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

# Enable logging
logger:

# Common restart switch for devices
switch:
  - platform: restart
    name: '${friendly_name} Restart'
