sensor:
  - platform: wifi_signal
    name: '${friendly_name} WiFi Signal'
    update_interval: 60s
  - platform: uptime
    name: '${friendly_name} Uptime'

text_sensor:
  - platform: wifi_info
    ip_address:
      name: '${friendly_name} IP Address'
    ssid:
      name: '${friendly_name} SSID'
    bssid:
      name: '${friendly_name} BSSID'
    mac_address:
      name: '${friendly_name} MAC Address'

binary_sensor:
  - platform: status
    name: '${friendly_name} Status'
