substitutions:
  hostname: "cam-1"
  mac_address_1: "A4:C1:38:BC:AA:14" 
  
esphome:
  name: $hostname

esp32:
  board: esp32dev
  framework:
    type: esp-idf


# Enable logging
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garage Control Hotspot"
    password: "jEvC7RTUNb7X"


# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password


# Enable logging
logger:


    
esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 10MHz

  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32


  # Image settings
  name: $hostname
  resolution: 800x600
  jpeg_quality: 10
  idle_framerate: 0.1fps
  


# LED
output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4
    
light:
  - platform: binary
    output: gpio_4
    name: $hostname light
    


    
# Bluetooth Proxy
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true
  


# ESP32 Bluetooth Low Energy Tracker Hub
sensor:
  - platform: pvvx_mithermometer
    mac_address: $mac_address_1
    temperature:
      name: $mac_address_1 "Temperature"
    humidity:
      name: $mac_address_1 "Humidity"
    battery_level:
      name: $mac_address_1 "Battery-Level"
    battery_voltage:
      name: $mac_address_1 "Battery-Voltage"
    signal_strength:
      name: $mac_address_1 "Signal"
