---
substitutions:
  name: 'stair-closet-camera'
  friendly_name: 'Stair Closet Camera'

esphome:
  name: $name
  name_add_mac_suffix: true

esp32:
  board: esp-wrover-kit
  psram:
    mode: octal
  framework:
    type: arduino

packages:
  base_config: !include ../../common/base_config.yaml
  wifi_fallback: !include ../../common/wifi_fallback.yaml
  common_sensors: !include ../../common/common_sensors.yaml

esp32_camera:
  external_clock:
    pin: GPIO21
    frequency: 20MHz

  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO4, GPIO5, GPIO18, GPIO19, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22

  # Image settings
  name: '$name Camera'
  resolution: 800X600
  jpeg_quality: 25  # best 10 to poorest 63
  max_framerate: 8.0fps
  idle_framerate: 0.1fps
  vertical_flip: false
  horizontal_mirror: false

# Available GPIO on the board are 12, 13, 14 & 15.
# WARNING: GPIO0 / GPIO4 / GPIO12 is a Strapping PIN and should be avoided.
# Attaching external pullup/down resistors to strapping pins
# can cause unexpected failures.
# https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins

output:
  - platform: gpio
    pin:
      number: GPIO02
      inverted: false
    id: blue_led

light:
  - platform: binary
    output: blue_led
    name: '$name Blue LED'
switch:
  # Transistor Base
  - platform: gpio
    pin:
      number: 13
    id: transistor_base
    name: '$name Transistor Base'

binary_sensor:
  - platform: gpio
    name: '$name Door Sensor'
    id: 'door_sensor'
    device_class: door
    pin:
      number: 14
      mode: INPUT_PULLUP

    on_state:
      then:
        - if:
            condition:
              binary_sensor.is_on: door_sensor
            then:
              - switch.turn_on: transistor_base
            else:
              - switch.turn_off: transistor_base

